name: cm3070
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - pandas
  - pytest
  - jupyterlab
  - joblib
  - uvicorn
  - scikit-learn=1.9.0
  - seaborn
  - fastapi
  - numpy
  - nbdime
  - matplotlib
  - notebook
  - httpx2
